# Generated by Django 5.1 on 2024-08-29 15:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20, message='Max 20 symbols')], verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MaxLengthValidator(50, message='Max 50 symbols')], verbose_name='Slug')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MaxLengthValidator(50, message='Max 50 symbols')], verbose_name='Slug')),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_visible', models.BooleanField(choices=[(False, 'Hide'), (True, 'Visible')], default=0, verbose_name='Status')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('programming_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='search_site.language')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Min 5 symbols'), django.core.validators.MaxLengthValidator(20, message='Max 20 symbols')], verbose_name='Slug')),
                ('image', models.FileField(blank=True, upload_to='users_images/')),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('frameworks', models.CharField(max_length=255)),
                ('experience', models.BigIntegerField(blank=True)),
                ('about_me', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('last_visited', models.DateTimeField(blank=True)),
                ('visible', models.BooleanField(blank=True, default=False)),
                ('is_online', models.BooleanField(blank=True, default=False)),
                ('confirmation', models.BooleanField(blank=True, default=False)),
                ('programming_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='search_site.language')),
                ('usertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='search_site.usercategory')),
            ],
        ),
    ]
